#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# build-client.sh — Build the Reactory PWA Client for Electron
#
# Builds the client with Electron-specific environment variables
# then copies the output to build/client.
# ──────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_DIR/build/client"

# Configuration — can be overridden via env vars or CLI args
REACTORY_CONFIG_ID="${REACTORY_CONFIG_ID:-reactory}"
REACTORY_THEME_ID="${REACTORY_THEME_ID:-$REACTORY_CONFIG_ID}"

# Resolve the PWA client path
REACTORY_CLIENT="${REACTORY_CLIENT:-$(dirname "$PROJECT_DIR")/reactory-pwa-client}"

if [ ! -d "$REACTORY_CLIENT" ]; then
  echo "❌ ERROR: Reactory PWA Client not found at $REACTORY_CLIENT"
  echo "   Set REACTORY_CLIENT environment variable to the correct path."
  exit 1
fi

echo "══════════════════════════════════════════════════════════"
echo "  Building Reactory PWA Client for Electron"
echo "  Config: $REACTORY_CONFIG_ID"
echo "  Theme:  $REACTORY_THEME_ID"
echo "  Source: $REACTORY_CLIENT"
echo "  Output: $BUILD_DIR"
echo "══════════════════════════════════════════════════════════"

# ── Step 1: Clean ──
echo ""
echo "🧹 Cleaning previous client build…"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# ── Step 2: Create Electron env file ──
ELECTRON_ENV_DIR="$REACTORY_CLIENT/config/env/$REACTORY_CONFIG_ID"
ELECTRON_ENV_FILE="$ELECTRON_ENV_DIR/.env.electron"

# Read theme colors from the existing .env.local for this config
PRIMARY_COLOR="#f95e20"
SECONDARY_COLOR="#424242"
BG_COLOR="#424242"
CLIENT_KEY="$REACTORY_CONFIG_ID"
CLIENT_PASSWORD=""
LOCAL_ENV_FILE="$ELECTRON_ENV_DIR/.env.local"

if [ -f "$LOCAL_ENV_FILE" ]; then
  PRIMARY_COLOR=$(grep "^REACT_APP_THEME_PRIMARY=" "$LOCAL_ENV_FILE" | cut -d= -f2 | tr -d "'" | tr -d '"' || echo "#f95e20")
  SECONDARY_COLOR=$(grep "^REACT_APP_THEME_SECONDARY=" "$LOCAL_ENV_FILE" | cut -d= -f2 | tr -d "'" | tr -d '"' || echo "#424242")
  BG_COLOR=$(grep "^REACT_APP_THEME_BG=" "$LOCAL_ENV_FILE" | cut -d= -f2 | tr -d "'" | tr -d '"' || echo "#424242")
  CLIENT_KEY=$(grep "^REACT_APP_CLIENT_KEY=" "$LOCAL_ENV_FILE" | cut -d= -f2 | tr -d "'" | tr -d '"' || echo "$REACTORY_CONFIG_ID")
  CLIENT_PASSWORD=$(grep "^REACT_APP_CLIENT_PASSWORD=" "$LOCAL_ENV_FILE" | cut -d= -f2 | tr -d "'" | tr -d '"' || true)
fi

# Capitalize config ID (portable — works with Bash 3.x on macOS)
APP_TITLE="$(echo "$REACTORY_CONFIG_ID" | awk '{print toupper(substr($0,1,1)) substr($0,2)}') Desktop"

echo ""
echo "📝 Creating Electron environment file…"
mkdir -p "$ELECTRON_ENV_DIR"
cat > "$ELECTRON_ENV_FILE" << ENVEOF
# Reactory PWA Client — Electron Build Environment
# Auto-generated by build-client.sh for config: $REACTORY_CONFIG_ID
REACT_APP_API_ENDPOINT=http://localhost:4000
REACT_APP_CDN=http://localhost:4000/cdn/
REACT_APP_CLIENT_KEY=${CLIENT_KEY}
REACT_APP_CLIENT_PASSWORD=${CLIENT_PASSWORD}
REACT_APP_TITLE=${REACTORY_CONFIG_ID}:${REACTORY_CONFIG_ID}.application.title
REACT_APP_THEME=${REACTORY_THEME_ID}
REACT_APP_THEME_PRIMARY=${PRIMARY_COLOR}
REACT_APP_THEME_SECONDARY=${SECONDARY_COLOR}
REACT_APP_THEME_BG=${BG_COLOR}
REACT_APP_SHORTNAME=${REACTORY_CONFIG_ID}:${REACTORY_CONFIG_ID}.application.shortName
REACT_APP_APP_TITLE=${APP_TITLE}
REACT_APP_DISABLE_SW=true

# Build settings
PORT=3000
NODE_ENV=production
GENERATE_SOURCEMAP=false
CI=false

# Electron-specific
REACT_APP_RUNTIME=electron
ENVEOF
echo "   Created: $ELECTRON_ENV_FILE"

# ── Step 3: Build the client ──
echo ""
echo "🔨 Building client (this may take a few minutes)…"
cd "$REACTORY_CLIENT"

# Use the existing build script with the electron environment
if [ -f "bin/build.sh" ]; then
  bash bin/build.sh "$REACTORY_CONFIG_ID" electron
else
  echo "❌ ERROR: bin/build.sh not found in $REACTORY_CLIENT"
  exit 1
fi

# ── Step 4: Copy built output ──
echo ""
echo "📦 Copying build output…"
CLIENT_BUILD_OUTPUT="$REACTORY_CLIENT/build/$REACTORY_CONFIG_ID/electron"
if [ ! -d "$CLIENT_BUILD_OUTPUT" ]; then
  echo "⚠️  Expected build output at $CLIENT_BUILD_OUTPUT not found."
  echo "   Checking for alternative build locations…"
  
  # Try common alternatives
  for alt in "$REACTORY_CLIENT/build/reactory/production" "$REACTORY_CLIENT/build/reactory/local" "$REACTORY_CLIENT/build"; do
    if [ -d "$alt" ] && [ -f "$alt/index.html" ]; then
      CLIENT_BUILD_OUTPUT="$alt"
      echo "   Found build at: $alt"
      break
    fi
  done
fi

if [ -d "$CLIENT_BUILD_OUTPUT" ] && [ -f "$CLIENT_BUILD_OUTPUT/index.html" ]; then
  cp -r "$CLIENT_BUILD_OUTPUT/"* "$BUILD_DIR/"
  echo "   Copied $(find "$BUILD_DIR" -type f | wc -l | tr -d ' ') files"
else
  echo "❌ ERROR: Client build output not found or missing index.html"
  exit 1
fi

# ── Step 5: Patch for Electron ──
echo ""
echo "🔧 Applying Electron patches…"

# Remove service worker registration if it was built
if [ -f "$BUILD_DIR/service-worker.js" ]; then
  rm "$BUILD_DIR/service-worker.js"
  echo "   Removed service-worker.js"
fi

echo ""
echo "══════════════════════════════════════════════════════════"
echo "  ✅ Client build complete"
echo "  Output: $BUILD_DIR"
echo "  Files:  $(find "$BUILD_DIR" -type f | wc -l | tr -d ' ')"
echo "══════════════════════════════════════════════════════════"
